extern void initGPS();
extern boolean getGPSdata();
extern String getlat();
extern String getlong();
extern String getalt();
extern String getgpsTime();
extern String getnumsatellites();
extern String getspeed();
extern String getage();
